### ISSUE TITLE
이메일 인증 오류

### ISSUE THREAD

**Issue by googoo81** [GSM-MSG/GAUTH_BackEnd#111]
비밀번호 이메일을 인증 했을때
![image](https://user-images.githubusercontent.com/101445027/224595234-75b2bf94-3a3b-48bb-9607-7629dbc95dc2.png)
이런 식으로 인증하는 링크가 오지 않고 그냥 "mail"단어로만 옵니다
![KakaoTalk_20230313_113433613](https://user-images.githubusercontent.com/101445027/224595408-ccdb4bf7-e649-4edf-adf8-e3449ac07ba9.jpg)

**Comment by baekteun** [comment]
와 엿됐다
