### ISSUE TITLE
비밀번호 블라인드 처리 오류

### ISSUE THREAD

**Issue by donguk1207** [GSM-MSG/GAUTH_BackEnd#154]
![gauth](https://user-images.githubusercontent.com/106513119/235362633-0f018568-5f14-465e-96e1-e18632fca118.png)
![gauth`](https://user-images.githubusercontent.com/106513119/235362639-da93a367-5613-40fa-8de0-a01037bf5e51.png)
비밀번호 블라인드 처리가 반대로 되어 있는 것 같습니다.

**Comment by baekteun** [comment]
안녕하세요, GAuth에 관심을 가져주셔서? 감사합니다.
하지만 해당 이슈는 [Dotori](https://github.com/Team-Ampersand/Dotori-client-v2/issues)
그리고 Client측에 이슈를 올려주셔야할거같습니다. 감사합니다 (_)
